import mysql from 'mysql2/promise';
import fs from 'fs/promises';
import path from 'path';
import dotenv from 'dotenv';
import { fileURLToPath } from 'url';

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const config = {
    host: process.env.DB_HOST || 'localhost',
    user: process.env.DB_USER || 'root',
    password: process.env.DB_PASS || '',
    database: process.env.DB_NAME || 'sng_logistics',
    port: process.env.DB_PORT || 3308
};

async function dump() {
    console.log(`Connecting to database ${config.database} on port ${config.port}...`);
    let connection;
    try {
        connection = await mysql.createConnection(config);
    } catch (err) {
        console.error('Connection failed:', err.message);
        process.exit(1);
    }

    let output = `-- SNG Logistics Database Dump\n-- Generated by custom Node.js script\n\n`;
    output += `SET FOREIGN_KEY_CHECKS=0;\n\n`;

    try {
        const [tables] = await connection.query('SHOW TABLES');
        const tableNames = tables.map(t => Object.values(t)[0]);

        for (const tableName of tableNames) {
            console.log(`Processing table: ${tableName}`);

            // Structure
            const [createResult] = await connection.query(`SHOW CREATE TABLE \`${tableName}\``);
            output += `DROP TABLE IF EXISTS \`${tableName}\`;\n`;
            output += `${createResult[0]['Create Table']};\n\n`;

            // Data
            const [rows] = await connection.query(`SELECT * FROM \`${tableName}\``);
            if (rows.length > 0) {
                output += `INSERT INTO \`${tableName}\` VALUES `;
                const values = rows.map(row => {
                    const rowValues = Object.values(row).map(val => {
                        if (val === null) return 'NULL';
                        if (typeof val === 'number') return val;
                        if (val instanceof Date) return `'${val.toISOString().slice(0, 19).replace('T', ' ')}'`;
                        // Escape single quotes and backslashes
                        return `'${String(val).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
                    });
                    return `(${rowValues.join(',')})`;
                });
                output += values.join(',\n') + ';\n\n';
            }
        }

        output += `SET FOREIGN_KEY_CHECKS=1;\n`;

        await fs.writeFile('sng_logistics.sql', output);
        console.log('Success! Saved to sng_logistics.sql');
    } catch (err) {
        console.error('Export failed:', err);
    } finally {
        await connection.end();
    }
}

dump();
